Repository kir-dev/airsoft, pull requests merged in 2021-08, with the labels that each got.

#118 Fix docker image node version
  Dockerfile
Labels: devops

#126 Fix small js bug in post-index
  app/javascript/packs/post-index.js
Labels: bug

#130 Enhance event subsystem
  .rubocop.yml
  .rubocop_todo.yml
  app/controllers/events_controller.rb
  app/controllers/participations_controller.rb
  app/models/event.rb
  app/models/event_type.rb
  app/models/item.rb
  app/models/user.rb
  app/views/event_types/_form.html.erb
  app/views/events/_form.html.erb
  app/views/events/list.html.erb
  app/views/events/show.html.erb
  app/views/participations/_table.html.erb
  config/locales/translation_hu.yml
  db/migrate/20210818153234_add_registration_deadline_to_event.rb
  db/schema.rb
  test/fixtures/events.yml
  test/models/event_test.rb
Labels: enhancement
